// Generator script for 27 Sur-Ron products
const products = [
  // ===== I. LIGHT BEE FAMILY =====
  {
    id: "surron-light-bee-x-2018",
    slug: "surron-light-bee-x-2018-originale",
    nom: "Sur-Ron Light Bee X (Originale 2018/2020)",
    nom_en: "Sur-Ron Light Bee X (Original 2018/2020)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Off-Road 5kW 50cc",
    category_label_en: "Off-Road Mini-Cross 5kW 50cc Class",
    description: "Le modèle fondateur qui a lancé la révolution Sur-Ron. Moteur 5 kW, batterie 60V 32Ah, vitesse max 75 km/h pour seulement 50 kg. La plateforme emblématique qui a conquis le monde du tout-terrain électrique.",
    description_en: "The founding model that launched the Sur-Ron revolution. 5 kW motor, 60V 32Ah battery, 75 km/h top speed at just 50 kg. The iconic platform that conquered the electric off-road world.",
    highlight_subtitle: "5 kW • 75 km/h • 50 kg • Batterie 60V 32Ah",
    highlight_subtitle_en: "5 kW • 75 km/h • 50 kg • 60V 32Ah Battery",
    prix: 4290, prix_promo: 4090,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Off-Road Uniquement (Sans Permis)",
    license_label_en: "Off-Road Use Only (No License)",
    autonomie_km: 55, autonomie_city_km: 65, autonomie_highway_km: 35,
    vitesse_max: 75, acceleration_0_100_s: 6.5, acceleration_0_50_s: 2.8,
    stock: 3, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 50, payload_kg: 100, temps_charge_h: 4,
    moteur: "Moteur électrique brushless 5 kW crête",
    batterie: "Pack Li-ion 1.92 kWh 60V 32Ah (Lithium-Ion NMC)",
    battery_kwh: 1.92, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 3, motor_peak_kw: 5, motor_hp: 6.8, torque_nm: 130,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.4, review_count: 156, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-light-bee-x-2022",
    slug: "surron-light-bee-x-2022-sinewave",
    nom: "Sur-Ron Light Bee X (Upgrade 2021/2022)",
    nom_en: "Sur-Ron Light Bee X (Sine Wave Upgrade 2021/2022)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Off-Road 6kW Sine Wave X",
    category_label_en: "Off-Road Mini-Cross 6kW Sine Wave X Controller",
    description: "Version améliorée avec contrôleur Sine Wave X pour un couple supérieur et une réponse plus linéaire. Puissance portée à 6 kW, batterie 60V 32Ah. Le même châssis léger de 50 kg avec une électronique de pointe.",
    description_en: "Improved version with Sine Wave X controller for superior torque and linear response. Power increased to 6 kW, 60V 32Ah battery. Same lightweight 50 kg chassis with cutting-edge electronics.",
    highlight_subtitle: "6 kW • Sine Wave X • 60V 32Ah • 50 kg",
    highlight_subtitle_en: "6 kW • Sine Wave X • 60V 32Ah • 50 kg",
    prix: 4590, prix_promo: 4390,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Off-Road Uniquement (Sans Permis)",
    license_label_en: "Off-Road Use Only (No License)",
    autonomie_km: 55, autonomie_city_km: 65, autonomie_highway_km: 35,
    vitesse_max: 78, acceleration_0_100_s: 5.8, acceleration_0_50_s: 2.5,
    stock: 5, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 50, payload_kg: 100, temps_charge_h: 4,
    moteur: "Moteur électrique brushless 6 kW crête contrôleur Sine Wave X",
    batterie: "Pack Li-ion 1.92 kWh 60V 32Ah (Lithium-Ion NMC)",
    battery_kwh: 1.92, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 3.5, motor_peak_kw: 6, motor_hp: 8.2, torque_nm: 150,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.5, review_count: 98, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-light-bee-x-2024",
    slug: "surron-light-bee-x-2024-batterie-amelioree",
    nom: "Sur-Ron Light Bee X (Version 2023/2024)",
    nom_en: "Sur-Ron Light Bee X (Improved Battery 2023/2024)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Off-Road 6kW 60V 38.5Ah",
    category_label_en: "Off-Road Mini-Cross 6kW 60V 38.5Ah",
    description: "Batterie améliorée 60V 38.5Ah pour une autonomie étendue à ~70 km. Même moteur 6 kW éprouvé dans un châssis raffiné. Le compromis parfait entre légèreté et endurance pour le tout-terrain.",
    description_en: "Improved 60V 38.5Ah battery for extended range up to ~70 km. Same proven 6 kW motor in a refined chassis. The perfect balance between lightness and endurance for off-road.",
    highlight_subtitle: "6 kW • 70 km d'autonomie • 60V 38.5Ah",
    highlight_subtitle_en: "6 kW • 70 km range • 60V 38.5Ah",
    prix: 4890, prix_promo: 4690,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Off-Road Uniquement (Sans Permis)",
    license_label_en: "Off-Road Use Only (No License)",
    autonomie_km: 70, autonomie_city_km: 80, autonomie_highway_km: 45,
    vitesse_max: 78, acceleration_0_100_s: 5.6, acceleration_0_50_s: 2.4,
    stock: 7, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 52, payload_kg: 100, temps_charge_h: 4.5,
    moteur: "Moteur électrique brushless 6 kW crête",
    batterie: "Pack Li-ion 2.31 kWh 60V 38.5Ah (Lithium-Ion NMC)",
    battery_kwh: 2.31, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 3.5, motor_peak_kw: 6, motor_hp: 8.2, torque_nm: 150,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.6, review_count: 74, featured: false, bestseller: true, is_new: false
  },
  {
    id: "surron-light-bee-x-2025",
    slug: "surron-light-bee-x-2025-60v-40ah",
    nom: "Sur-Ron Light Bee X (Version 2025)",
    nom_en: "Sur-Ron Light Bee X (2025 Version)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Off-Road 8kW Crête 266 Nm",
    category_label_en: "Off-Road Mini-Cross 8kW Peak 266 Nm",
    description: "Intégration batterie 60V 40Ah de dernière génération. Puissance crête de 8 kW et couple à la roue de 266 Nm. La Light Bee X dans sa version la plus aboutie avant la refonte complète de 2026.",
    description_en: "Latest-gen 60V 40Ah battery integration. 8 kW peak power and 266 Nm wheel torque. The most refined Light Bee X before the complete 2026 redesign.",
    highlight_subtitle: "8 kW crête • 266 Nm • 60V 40Ah",
    highlight_subtitle_en: "8 kW peak • 266 Nm • 60V 40Ah",
    prix: 5290, prix_promo: 5090,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Off-Road Uniquement (Sans Permis)",
    license_label_en: "Off-Road Use Only (No License)",
    autonomie_km: 75, autonomie_city_km: 85, autonomie_highway_km: 50,
    vitesse_max: 80, acceleration_0_100_s: 5.2, acceleration_0_50_s: 2.2,
    stock: 10, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 53, payload_kg: 100, temps_charge_h: 4.5,
    moteur: "Moteur électrique brushless 8 kW crête couple 266 Nm à la roue",
    batterie: "Pack Li-ion 2.4 kWh 60V 40Ah (Lithium-Ion NMC)",
    battery_kwh: 2.4, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 4, motor_peak_kw: 8, motor_hp: 10.9, torque_nm: 266,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.7, review_count: 45, featured: true, bestseller: true, is_new: false
  },
  {
    id: "surron-light-bee-x-2026",
    slug: "surron-light-bee-x-2026-72v-35ah",
    nom: "Sur-Ron Light Bee X (Génération 2026)",
    nom_en: "Sur-Ron Light Bee X (2026 Generation)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Off-Road 10kW 72V 295 Nm",
    category_label_en: "Off-Road Mini-Cross 10kW 72V 295 Nm",
    description: "Dernière génération : passage à la plateforme 10 kW avec batterie 72V 35Ah. Vitesse max 80 km/h et couple à la roue de 295 Nm. La Light Bee X n'a jamais été aussi puissante. Nouvelle architecture électronique et refroidissement optimisé.",
    description_en: "Latest generation: upgrade to 10 kW platform with 72V 35Ah battery. 80 km/h top speed and 295 Nm wheel torque. The Light Bee X has never been this powerful. New electronics architecture and optimized cooling.",
    highlight_subtitle: "10 kW • 72V 35Ah • 295 Nm • NOUVEAU 2026",
    highlight_subtitle_en: "10 kW • 72V 35Ah • 295 Nm • NEW 2026",
    prix: 5990, prix_promo: 5790,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Off-Road Uniquement (Sans Permis)",
    license_label_en: "Off-Road Use Only (No License)",
    autonomie_km: 80, autonomie_city_km: 90, autonomie_highway_km: 55,
    vitesse_max: 80, acceleration_0_100_s: 4.8, acceleration_0_50_s: 2.0,
    stock: 12, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 55, payload_kg: 100, temps_charge_h: 5,
    moteur: "Moteur électrique brushless 10 kW crête couple 295 Nm à la roue",
    batterie: "Pack Li-ion 2.52 kWh 72V 35Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 2.52, battery_voltage: 72, battery_removable: true,
    motor_nominal_kw: 5, motor_peak_kw: 10, motor_hp: 13.6, torque_nm: 295,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport", "Off-Road Pro"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.8, review_count: 18, featured: true, bestseller: true, is_new: true
  },
  // Light Bee L1E Homologuées
  {
    id: "surron-light-bee-l1e-2020",
    slug: "surron-light-bee-l1e-2020-homologuee",
    nom: "Sur-Ron Light Bee L1E Homologuée (2020)",
    nom_en: "Sur-Ron Light Bee L1E Road-Legal (2020)",
    brand: "Sur-Ron",
    category_label: "Mini-Moto Homologuée L1e 45 km/h Route",
    category_label_en: "L1e Road-Legal Mini-Moto 45 km/h",
    description: "Version homologuée route de la Light Bee X. Bridée à 45 km/h pour la législation 50cc. Kit route complet : phares, clignotants, plaque d'immatriculation. Batterie 60V 32Ah. Permis AM suffisant.",
    description_en: "Road-legal version of the Light Bee X. Restricted to 45 km/h for 50cc legislation. Complete road kit: headlights, indicators, license plate. 60V 32Ah battery. AM license sufficient.",
    highlight_subtitle: "45 km/h • Homologuée L1e • Kit route complet • Permis AM",
    highlight_subtitle_en: "45 km/h • L1e Road-Legal • Full Road Kit • AM License",
    prix: 4790, prix_promo: 4590,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "AM",
    license_label_fr: "Permis AM (50cc Électrique Homologué)",
    license_label_en: "AM License (50cc Electric Road-Legal)",
    autonomie_km: 50, autonomie_city_km: 60, autonomie_highway_km: 30,
    vitesse_max: 45, acceleration_0_100_s: 8.5, acceleration_0_50_s: 3.5,
    stock: 4, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 55, payload_kg: 100, temps_charge_h: 4,
    moteur: "Moteur électrique brushless 5 kW bridé 45 km/h",
    batterie: "Pack Li-ion 1.92 kWh 60V 32Ah (Lithium-Ion NMC)",
    battery_kwh: 1.92, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 3, motor_peak_kw: 5, motor_hp: 6.8, torque_nm: 130,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard"],
    certifications: ["CE", "UN 38.3", "UL 2849", "L1e"],
    rating: 4.3, review_count: 67, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-light-bee-l1e-2023",
    slug: "surron-light-bee-l1e-2023-homologuee",
    nom: "Sur-Ron Light Bee L1E Homologuée (2023)",
    nom_en: "Sur-Ron Light Bee L1E Road-Legal (2023)",
    brand: "Sur-Ron",
    category_label: "Mini-Moto Homologuée L1e 60V 38.5Ah",
    category_label_en: "L1e Road-Legal Mini-Moto 60V 38.5Ah",
    description: "Version 2023 avec batterie améliorée 60V 38.5Ah pour 65 km d'autonomie. Limitée à 45 km/h sur route (débridable hors route à 75 km/h). Kit route complet avec éclairage LED et plaque.",
    description_en: "2023 version with improved 60V 38.5Ah battery for 65 km range. Limited to 45 km/h on road (de-restrictable off-road to 75 km/h). Full road kit with LED lighting and plate.",
    highlight_subtitle: "65 km autonomie • L1e • Débridable 75 km/h hors route",
    highlight_subtitle_en: "65 km range • L1e • De-restrictable 75 km/h off-road",
    prix: 5190, prix_promo: 4990,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "AM",
    license_label_fr: "Permis AM (50cc Électrique Homologué)",
    license_label_en: "AM License (50cc Electric Road-Legal)",
    autonomie_km: 65, autonomie_city_km: 75, autonomie_highway_km: 40,
    vitesse_max: 45, acceleration_0_100_s: 8.0, acceleration_0_50_s: 3.2,
    stock: 6, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 56, payload_kg: 100, temps_charge_h: 4.5,
    moteur: "Moteur électrique brushless 6 kW bridé 45 km/h",
    batterie: "Pack Li-ion 2.31 kWh 60V 38.5Ah (Lithium-Ion NMC)",
    battery_kwh: 2.31, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 3.5, motor_peak_kw: 6, motor_hp: 8.2, torque_nm: 150,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3", "UL 2849", "L1e"],
    rating: 4.5, review_count: 52, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-light-bee-l1e-2026",
    slug: "surron-light-bee-l1e-2026-homologuee",
    nom: "Sur-Ron Light Bee L1E Homologuée (2025/2026)",
    nom_en: "Sur-Ron Light Bee L1E Road-Legal (2025/2026)",
    brand: "Sur-Ron",
    category_label: "Mini-Moto Homologuée L1e 60V 40Ah LED",
    category_label_en: "L1e Road-Legal Mini-Moto 60V 40Ah LED",
    description: "Dernière version homologuée avec batterie 60V 40Ah et moteur crête 6 kW. Éclairage LED amélioré pour une visibilité optimale. Bridée en nominal pour la législation L1e. La mini-moto route la plus aboutie de sa catégorie.",
    description_en: "Latest road-legal version with 60V 40Ah battery and 6 kW peak motor. Enhanced LED lighting for optimal visibility. Restricted for L1e legislation. The most refined road-legal mini-moto in its class.",
    highlight_subtitle: "60V 40Ah • LED amélioré • L1e 2026 • Permis AM",
    highlight_subtitle_en: "60V 40Ah • Enhanced LED • L1e 2026 • AM License",
    prix: 5490, prix_promo: 5290,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "AM",
    license_label_fr: "Permis AM (50cc Électrique Homologué)",
    license_label_en: "AM License (50cc Electric Road-Legal)",
    autonomie_km: 70, autonomie_city_km: 80, autonomie_highway_km: 45,
    vitesse_max: 45, acceleration_0_100_s: 7.5, acceleration_0_50_s: 3.0,
    stock: 8, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 57, payload_kg: 100, temps_charge_h: 4.5,
    moteur: "Moteur électrique brushless 6 kW crête bridé L1e",
    batterie: "Pack Li-ion 2.4 kWh 60V 40Ah (Lithium-Ion NMC)",
    battery_kwh: 2.4, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 4, motor_peak_kw: 6, motor_hp: 8.2, torque_nm: 160,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3", "UL 2849", "L1e"],
    rating: 4.6, review_count: 28, featured: true, bestseller: false, is_new: true
  },
  // Light Bee S Youth
  {
    id: "surron-light-bee-s-youth",
    slug: "surron-light-bee-s-youth-initiale",
    nom: "Sur-Ron Light Bee S (Youth - Version Initiale)",
    nom_en: "Sur-Ron Light Bee S (Youth - Initial Version)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Jeunesse 3kW 48V Roues 17\"",
    category_label_en: "Youth Mini-Cross 3kW 48V 17\" Wheels",
    description: "Modèle réduit conçu pour les jeunes pilotes. Moteur 3 kW, batterie 48V 20Ah, vitesse max 50 km/h. Roues de 17 pouces pour une prise en main facile et sécurisée. L'introduction parfaite au monde du deux-roues électrique.",
    description_en: "Reduced model designed for young riders. 3 kW motor, 48V 20Ah battery, 50 km/h top speed. 17-inch wheels for easy and safe handling. The perfect introduction to the electric two-wheeler world.",
    highlight_subtitle: "3 kW • 50 km/h • 48V 20Ah • Roues 17\"",
    highlight_subtitle_en: "3 kW • 50 km/h • 48V 20Ah • 17\" Wheels",
    prix: 2990, prix_promo: 2790,
    eco_bonus_eligible: true, max_eco_bonus: 300,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Privé / Jeunesse (Sans Permis)",
    license_label_en: "Private Use / Youth (No License)",
    autonomie_km: 35, autonomie_city_km: 45, autonomie_highway_km: 20,
    vitesse_max: 50, acceleration_0_100_s: 8.0, acceleration_0_50_s: 3.5,
    stock: 5, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 40, payload_kg: 70, temps_charge_h: 3.5,
    moteur: "Moteur électrique brushless 3 kW",
    batterie: "Pack Li-ion 0.96 kWh 48V 20Ah (Lithium-Ion NMC)",
    battery_kwh: 0.96, battery_voltage: 48, battery_removable: true,
    motor_nominal_kw: 2, motor_peak_kw: 3, motor_hp: 4.1, torque_nm: 80,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 420 renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.5, review_count: 34, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-light-bee-s-youth-2024",
    slug: "surron-light-bee-s-youth-2024-finale",
    nom: "Sur-Ron Light Bee S (Youth - Version Finale 2024)",
    nom_en: "Sur-Ron Light Bee S (Youth - Final 2024 Edition)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Jeunesse 48V 24Ah Édition Finale",
    category_label_en: "Youth Mini-Cross 48V 24Ah Final Edition",
    description: "Version finale de la Light Bee S Youth avec batterie poussée à 48V 24Ah pour une autonomie accrue. Modèle idéal pour les adolescents avant sa fin de production globale. Dernière opportunité.",
    description_en: "Final version of the Light Bee S Youth with 48V 24Ah battery for increased range. Ideal model for teenagers before global end of production. Last opportunity.",
    highlight_subtitle: "48V 24Ah • Édition Finale • Adolescents",
    highlight_subtitle_en: "48V 24Ah • Final Edition • Youth Riders",
    prix: 3290, prix_promo: 3090,
    eco_bonus_eligible: true, max_eco_bonus: 300,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Privé / Jeunesse (Sans Permis)",
    license_label_en: "Private Use / Youth (No License)",
    autonomie_km: 42, autonomie_city_km: 52, autonomie_highway_km: 25,
    vitesse_max: 50, acceleration_0_100_s: 7.5, acceleration_0_50_s: 3.2,
    stock: 2, stock_status: "in_showroom",
    delivery_time_label: "Derniers exemplaires au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "Last units at Paris Showroom • 48-72h delivery",
    poids_kg: 41, payload_kg: 70, temps_charge_h: 3.5,
    moteur: "Moteur électrique brushless 3 kW",
    batterie: "Pack Li-ion 1.15 kWh 48V 24Ah (Lithium-Ion NMC)",
    battery_kwh: 1.15, battery_voltage: 48, battery_removable: true,
    motor_nominal_kw: 2, motor_peak_kw: 3, motor_hp: 4.1, torque_nm: 85,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 420 renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.6, review_count: 21, featured: false, bestseller: false, is_new: false
  },
  // ===== II. LIGHT BEE 2 (Nouvelle Génération 2026) =====
  {
    id: "surron-light-bee-2-offroad-2026",
    slug: "surron-light-bee-2-offroad-2026",
    nom: "Sur-Ron Light Bee 2 Off-Road (2026)",
    nom_en: "Sur-Ron Light Bee 2 Off-Road (2026)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Nouvelle Génération Châssis Renforcé",
    category_label_en: "New Gen Off-Road Mini-Cross Reinforced Chassis",
    description: "Plateforme entièrement redessinée pour 2026. Châssis rigidifié, intégration technologique native, batterie haute tension et suspensions de course revues. La nouvelle référence du mini-cross électrique.",
    description_en: "Completely redesigned platform for 2026. Reinforced chassis, native tech integration, high-voltage battery and revised race suspensions. The new benchmark for electric mini-cross.",
    highlight_subtitle: "NOUVEAU 2026 • Châssis renforcé • Suspensions race",
    highlight_subtitle_en: "NEW 2026 • Reinforced Chassis • Race Suspension",
    prix: 6990, prix_promo: 6790,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Off-Road Uniquement (Sans Permis)",
    license_label_en: "Off-Road Use Only (No License)",
    autonomie_km: 85, autonomie_city_km: 95, autonomie_highway_km: 55,
    vitesse_max: 85, acceleration_0_100_s: 4.5, acceleration_0_50_s: 1.9,
    stock: 15, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 56, payload_kg: 100, temps_charge_h: 4,
    moteur: "Moteur électrique brushless nouvelle génération 12 kW crête",
    batterie: "Pack Li-ion 3.0 kWh 72V 42Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 3.0, battery_voltage: 72, battery_removable: true,
    motor_nominal_kw: 6, motor_peak_kw: 12, motor_hp: 16.3, torque_nm: 310,
    motor_type: "Moteur brushless à aimants permanents nouvelle génération", transmission: "Chaîne 428H renforcée X-Ring",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport", "Off-Road Pro"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.9, review_count: 8, featured: true, bestseller: true, is_new: true
  },
  {
    id: "surron-light-bee-2-homologuee-2026",
    slug: "surron-light-bee-2-homologuee-2026",
    nom: "Sur-Ron Light Bee 2 Homologuée Route (2026)",
    nom_en: "Sur-Ron Light Bee 2 Road-Legal (2026)",
    brand: "Sur-Ron",
    category_label: "Mini-Moto Homologuée L1e Nouvelle Architecture",
    category_label_en: "L1e Road-Legal Mini-Moto New Architecture",
    description: "Version conforme aux normes routières européennes de la nouvelle architecture Light Bee 2. Kit route complet avec éclairage LED, clignotants, plaque et rétroviseurs. La révolution Light Bee 2 enfin homologuée pour la route.",
    description_en: "European road-legal version of the new Light Bee 2 architecture. Complete road kit with LED lighting, indicators, plate and mirrors. The Light Bee 2 revolution finally road-legal.",
    highlight_subtitle: "L1e 2026 • Homologuée route • Nouvelle plateforme",
    highlight_subtitle_en: "L1e 2026 • Road-Legal • New Platform",
    prix: 7290, prix_promo: 7090,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "AM",
    license_label_fr: "Permis AM (50cc Électrique Homologué)",
    license_label_en: "AM License (50cc Electric Road-Legal)",
    autonomie_km: 80, autonomie_city_km: 90, autonomie_highway_km: 50,
    vitesse_max: 45, acceleration_0_100_s: 7.0, acceleration_0_50_s: 2.8,
    stock: 10, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 60, payload_kg: 100, temps_charge_h: 4.5,
    moteur: "Moteur électrique brushless nouvelle génération bridé L1e",
    batterie: "Pack Li-ion 3.0 kWh 72V 42Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 3.0, battery_voltage: 72, battery_removable: true,
    motor_nominal_kw: 4, motor_peak_kw: 6, motor_hp: 8.2, torque_nm: 200,
    motor_type: "Moteur brushless à aimants permanents nouvelle génération", transmission: "Chaîne 428H renforcée X-Ring",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3", "UL 2849", "L1e"],
    rating: 4.8, review_count: 5, featured: true, bestseller: false, is_new: true
  },
  // ===== III. HYPER BEE FAMILY =====
  {
    id: "surron-hyper-bee-2025",
    slug: "surron-hyper-bee-2025-initiale",
    nom: "Sur-Ron Hyper Bee (Version Initiale 2025)",
    nom_en: "Sur-Ron Hyper Bee (Initial 2025 Version)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross Enfants/Ados 5kW 38 kg",
    category_label_en: "Kids/Teen Mini-Cross 5kW 38 kg",
    description: "La nouvelle mini-cross haut de gamme pour enfants et adolescents. Moteur 5 kW dans un châssis ultra-léger de 38 kg. Batterie 58V 22Ah. Le parfait tremplin vers la compétition tout-terrain électrique.",
    description_en: "The new premium mini-cross for kids and teens. 5 kW motor in an ultra-light 38 kg chassis. 58V 22Ah battery. The perfect springboard to electric off-road competition.",
    highlight_subtitle: "5 kW • 38 kg plume • 58V 22Ah • Enfants/Ados",
    highlight_subtitle_en: "5 kW • 38 kg featherweight • 58V 22Ah • Kids/Teens",
    prix: 3690, prix_promo: 3490,
    eco_bonus_eligible: true, max_eco_bonus: 300,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Privé / Jeunesse (Sans Permis)",
    license_label_en: "Private Use / Youth (No License)",
    autonomie_km: 40, autonomie_city_km: 50, autonomie_highway_km: 25,
    vitesse_max: 60, acceleration_0_100_s: 6.0, acceleration_0_50_s: 2.5,
    stock: 8, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 38, payload_kg: 70, temps_charge_h: 3.5,
    moteur: "Moteur électrique brushless 5 kW",
    batterie: "Pack Li-ion 1.28 kWh 58V 22Ah (Lithium-Ion NMC)",
    battery_kwh: 1.28, battery_voltage: 58, battery_removable: true,
    motor_nominal_kw: 3, motor_peak_kw: 5, motor_hp: 6.8, torque_nm: 110,
    motor_type: "Moteur brushless à aimants permanents", transmission: "Chaîne 420 renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.7, review_count: 15, featured: false, bestseller: false, is_new: true
  },
  {
    id: "surron-hyper-bee-x-2026",
    slug: "surron-hyper-bee-x-2026",
    nom: "Sur-Ron Hyper Bee X (Modèle 2026)",
    nom_en: "Sur-Ron Hyper Bee X (2026 Model)",
    brand: "Sur-Ron",
    category_label: "Mini-Cross 8kW 184 Nm Anti-Wheeling App",
    category_label_en: "Mini-Cross 8kW 184 Nm Anti-Wheeling App Control",
    description: "Moteur optimisé de 8 kW avec couple de 184 Nm et vitesse max 64 km/h. Système d'anti-wheeling électronique et contrôle parental via application mobile. La mini-cross la plus technologique du marché.",
    description_en: "Optimized 8 kW motor with 184 Nm torque and 64 km/h top speed. Electronic anti-wheeling system and parental control via mobile app. The most technological mini-cross on the market.",
    highlight_subtitle: "8 kW • 184 Nm • Anti-wheeling • Contrôle parental App",
    highlight_subtitle_en: "8 kW • 184 Nm • Anti-Wheeling • Parental App Control",
    prix: 4490, prix_promo: 4290,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Privé / Jeunesse (Sans Permis)",
    license_label_en: "Private Use / Youth (No License)",
    autonomie_km: 50, autonomie_city_km: 60, autonomie_highway_km: 30,
    vitesse_max: 64, acceleration_0_100_s: 5.0, acceleration_0_50_s: 2.1,
    stock: 10, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 40, payload_kg: 75, temps_charge_h: 3.5,
    moteur: "Moteur électrique brushless 8 kW couple 184 Nm",
    batterie: "Pack Li-ion 1.5 kWh 58V 26Ah (Lithium-Ion NMC)",
    battery_kwh: 1.5, battery_voltage: 58, battery_removable: true,
    motor_nominal_kw: 4, motor_peak_kw: 8, motor_hp: 10.9, torque_nm: 184,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 420 renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport", "Parent Control"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.8, review_count: 6, featured: true, bestseller: false, is_new: true
  },
  // ===== IV. ULTRA BEE FAMILY =====
  {
    id: "surron-ultra-bee-x-2023",
    slug: "surron-ultra-bee-x-2023-offroad",
    nom: "Sur-Ron Ultra Bee X (Tout-terrain 2023)",
    nom_en: "Sur-Ron Ultra Bee X (Off-Road 2023)",
    brand: "Sur-Ron",
    category_label: "Enduro Électrique 12.5kW Équivalent 125cc",
    category_label_en: "Electric Enduro 12.5kW 125cc Equivalent",
    description: "Le chaînon manquant entre Light Bee et Storm Bee. Moteur 12.5 kW, batterie 74V 55Ah, vitesse max 90 km/h pour seulement 85 kg. L'équivalent 125cc électrique le plus léger du marché.",
    description_en: "The missing link between Light Bee and Storm Bee. 12.5 kW motor, 74V 55Ah battery, 90 km/h top speed at just 85 kg. The lightest 125cc electric equivalent on the market.",
    highlight_subtitle: "12.5 kW • 90 km/h • 85 kg • 74V 55Ah",
    highlight_subtitle_en: "12.5 kW • 90 km/h • 85 kg • 74V 55Ah",
    prix: 8990, prix_promo: 8790,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A1_B",
    license_label_fr: "Permis A1 ou B + 7h (Équiv 125cc)",
    license_label_en: "License A1 or Car+7h (125cc Equivalent)",
    autonomie_km: 90, autonomie_city_km: 110, autonomie_highway_km: 60,
    vitesse_max: 90, acceleration_0_100_s: 4.2, acceleration_0_50_s: 1.8,
    stock: 6, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 85, payload_kg: 140, temps_charge_h: 5,
    moteur: "Moteur électrique brushless 12.5 kW crête couple 380 Nm",
    batterie: "Pack Li-ion 4.07 kWh 74V 55Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 4.07, battery_voltage: 74, battery_removable: true,
    motor_nominal_kw: 6, motor_peak_kw: 12.5, motor_hp: 17, torque_nm: 380,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 520 renforcée X-Ring",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport", "Off-Road"],
    certifications: ["CE", "UN 38.3", "UL 2849"],
    rating: 4.7, review_count: 38, featured: true, bestseller: true, is_new: false
  },
  {
    id: "surron-ultra-bee-t-2024",
    slug: "surron-ultra-bee-t-2024-trial",
    nom: "Sur-Ron Ultra Bee T (Trial / Trail 2024)",
    nom_en: "Sur-Ron Ultra Bee T (Trial / Trail 2024)",
    brand: "Sur-Ron",
    category_label: "Trial Électrique 125cc Rapports Adaptés",
    category_label_en: "Electric 125cc Trial with Adapted Gear Ratios",
    description: "Version configurée pour le franchissement technique avec rapports de transmission adaptés. Couple optimisé à bas régime pour le trial et le trail. Suspensions à grand débattement et protection renforcée du châssis.",
    description_en: "Configured for technical trail riding with adapted gear ratios. Low-RPM optimized torque for trial and trail. Long-travel suspension and reinforced chassis protection.",
    highlight_subtitle: "Trial • Rapports courts • Couple bas régime optimisé",
    highlight_subtitle_en: "Trial • Short Ratios • Optimized Low-RPM Torque",
    prix: 9290, prix_promo: 9090,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A1_B",
    license_label_fr: "Permis A1 ou B + 7h (Équiv 125cc)",
    license_label_en: "License A1 or Car+7h (125cc Equivalent)",
    autonomie_km: 75, autonomie_city_km: 90, autonomie_highway_km: 50,
    vitesse_max: 80, acceleration_0_100_s: 4.8, acceleration_0_50_s: 2.0,
    stock: 4, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 87, payload_kg: 140, temps_charge_h: 5,
    moteur: "Moteur électrique brushless 12.5 kW couple trial optimisé",
    batterie: "Pack Li-ion 4.07 kWh 74V 55Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 4.07, battery_voltage: 74, battery_removable: true,
    motor_nominal_kw: 6, motor_peak_kw: 12.5, motor_hp: 17, torque_nm: 420,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 520 renforcée X-Ring rapports courts",
    regen_braking: true, riding_modes: ["Eco", "Trial", "Trail", "Sport"],
    certifications: ["CE", "UN 38.3", "UL 2849"],
    rating: 4.6, review_count: 22, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-ultra-bee-r-2024",
    slug: "surron-ultra-bee-r-2024-supermotard",
    nom: "Sur-Ron Ultra Bee R (Road / Supermotard 2024)",
    nom_en: "Sur-Ron Ultra Bee R (Road / Supermoto 2024)",
    brand: "Sur-Ron",
    category_label: "Supermotard Électrique 125cc Pneus Slicks",
    category_label_en: "Electric 125cc Supermoto with Slick Tires",
    description: "Version supermotard avec pneus slicks 17 pouces pour la route, suspensions raffermies pour l'asphalte et freins surdimensionnés. L'Ultra Bee la plus polyvalente pour un usage mixte route et loisir.",
    description_en: "Supermoto version with 17-inch slick tires for road, firmened suspension for asphalt and oversized brakes. The most versatile Ultra Bee for mixed road and leisure use.",
    highlight_subtitle: "Supermotard • Pneus slicks 17\" • Suspensions route",
    highlight_subtitle_en: "Supermoto • 17\" Slick Tires • Road Suspension",
    prix: 9490, prix_promo: 9290,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A1_B",
    license_label_fr: "Permis A1 ou B + 7h (Équiv 125cc)",
    license_label_en: "License A1 or Car+7h (125cc Equivalent)",
    autonomie_km: 85, autonomie_city_km: 100, autonomie_highway_km: 60,
    vitesse_max: 90, acceleration_0_100_s: 4.0, acceleration_0_50_s: 1.7,
    stock: 5, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 86, payload_kg: 140, temps_charge_h: 5,
    moteur: "Moteur électrique brushless 12.5 kW crête couple 380 Nm",
    batterie: "Pack Li-ion 4.07 kWh 74V 55Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 4.07, battery_voltage: 74, battery_removable: true,
    motor_nominal_kw: 6, motor_peak_kw: 12.5, motor_hp: 17, torque_nm: 380,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Courroie carbone renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport", "Rain"],
    certifications: ["CE", "UN 38.3", "UL 2849", "Euro 5"],
    rating: 4.7, review_count: 31, featured: true, bestseller: false, is_new: false
  },
  {
    id: "surron-ultra-bee-l3e-2025",
    slug: "surron-ultra-bee-l3e-2025-homologuee",
    nom: "Sur-Ron Ultra Bee L3E Homologuée (2024/2025)",
    nom_en: "Sur-Ron Ultra Bee L3E Road-Legal (2024/2025)",
    brand: "Sur-Ron",
    category_label: "125cc Électrique Homologuée L3e Route Complète",
    category_label_en: "L3e Road-Legal 125cc Electric Full Road Kit",
    description: "Version homologuée L3e équivalente 125cc. Vitesse max 90 km/h, nécessite le permis B + formation ou permis A1. Éclairage complet, plaque, rétroviseurs et tout le nécessaire pour la route.",
    description_en: "L3e road-legal 125cc equivalent version. 90 km/h top speed, requires B license + training or A1 license. Full lighting, plate, mirrors and everything needed for the road.",
    highlight_subtitle: "L3E Homologuée • 90 km/h • Permis A1/B+7h",
    highlight_subtitle_en: "L3E Road-Legal • 90 km/h • A1/Car+7h License",
    prix: 9790, prix_promo: 9590,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A1_B",
    license_label_fr: "Permis A1 ou B + 7h (Équiv 125cc)",
    license_label_en: "License A1 or Car+7h (125cc Equivalent)",
    autonomie_km: 85, autonomie_city_km: 100, autonomie_highway_km: 60,
    vitesse_max: 90, acceleration_0_100_s: 4.2, acceleration_0_50_s: 1.8,
    stock: 7, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 90, payload_kg: 140, temps_charge_h: 5,
    moteur: "Moteur électrique brushless 12.5 kW crête homologué L3e",
    batterie: "Pack Li-ion 4.07 kWh 74V 55Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 4.07, battery_voltage: 74, battery_removable: true,
    motor_nominal_kw: 6, motor_peak_kw: 12.5, motor_hp: 17, torque_nm: 380,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 520 renforcée X-Ring",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3", "UL 2849", "Euro 5", "L3e"],
    rating: 4.6, review_count: 19, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-ultra-bee-c-2025",
    slug: "surron-ultra-bee-c-2025-enduro",
    nom: "Sur-Ron Ultra Bee C (Enduro 2025)",
    nom_en: "Sur-Ron Ultra Bee C (Enduro 2025)",
    brand: "Sur-Ron",
    category_label: "Enduro Forestier Couple Lissé 125cc",
    category_label_en: "Forest Enduro Smoothed Torque 125cc",
    description: "Modèle Enduro avec répartition du couple lissée pour la randonnée en forêt. Suspensions recalibrées pour le confort sur les longs parcours. Protection intégrale du châssis et garde au sol rehaussée.",
    description_en: "Enduro model with smoothed torque delivery for forest riding. Recalibrated suspension for comfort on long rides. Full chassis protection and increased ground clearance.",
    highlight_subtitle: "Enduro • Couple lissé • Suspensions confort • Forêt",
    highlight_subtitle_en: "Enduro • Smoothed Torque • Comfort Suspension • Forest",
    prix: 9990, prix_promo: 9790,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A1_B",
    license_label_fr: "Permis A1 ou B + 7h (Équiv 125cc)",
    license_label_en: "License A1 or Car+7h (125cc Equivalent)",
    autonomie_km: 95, autonomie_city_km: 115, autonomie_highway_km: 65,
    vitesse_max: 85, acceleration_0_100_s: 4.8, acceleration_0_50_s: 2.0,
    stock: 5, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 88, payload_kg: 140, temps_charge_h: 5,
    moteur: "Moteur électrique brushless 12.5 kW couple lissé enduro",
    batterie: "Pack Li-ion 4.44 kWh 74V 60Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 4.44, battery_voltage: 74, battery_removable: true,
    motor_nominal_kw: 6, motor_peak_kw: 12.5, motor_hp: 17, torque_nm: 400,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 520 renforcée X-Ring",
    regen_braking: true, riding_modes: ["Eco", "Enduro", "Trail", "Forest"],
    certifications: ["CE", "UN 38.3", "UL 2849"],
    rating: 4.8, review_count: 14, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-ultra-bee-hp-2026",
    slug: "surron-ultra-bee-hp-2026-high-performance",
    nom: "Sur-Ron Ultra Bee HP (High Performance 2026)",
    nom_en: "Sur-Ron Ultra Bee HP (High Performance 2026)",
    brand: "Sur-Ron",
    category_label: "Hyper-Enduro 24.5 kW 33ch 520 Nm Monstre",
    category_label_en: "Hyper-Enduro 24.5 kW 33hp 520 Nm Monster",
    description: "Puissance monstrueuse de 24.5 kW (33 ch) ! Batterie 74V 60Ah, couple de 520 Nm à la roue et autonomie étendue jusqu'à 140 km à basse vitesse. Le summum de la performance Sur-Ron pour pilotes experts.",
    description_en: "Monstrous 24.5 kW (33 hp) power! 74V 60Ah battery, 520 Nm wheel torque and extended range up to 140 km at low speed. The pinnacle of Sur-Ron performance for expert riders.",
    highlight_subtitle: "24.5 kW / 33 ch • 520 Nm • 140 km • MONSTRE",
    highlight_subtitle_en: "24.5 kW / 33 hp • 520 Nm • 140 km • MONSTER",
    prix: 12990, prix_promo: 12490,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A2",
    license_label_fr: "Permis A2 (Jusqu'à 35 kW)",
    license_label_en: "A2 License (Up to 35 kW)",
    autonomie_km: 140, autonomie_city_km: 160, autonomie_highway_km: 90,
    vitesse_max: 100, acceleration_0_100_s: 3.5, acceleration_0_50_s: 1.5,
    stock: 3, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 92, payload_kg: 140, temps_charge_h: 6,
    moteur: "Moteur électrique brushless 24.5 kW (33 ch) couple 520 Nm",
    batterie: "Pack Li-ion 4.44 kWh 74V 60Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 4.44, battery_voltage: 74, battery_removable: true,
    motor_nominal_kw: 12, motor_peak_kw: 24.5, motor_hp: 33, torque_nm: 520,
    motor_type: "Moteur brushless à aimants permanents haute performance", transmission: "Chaîne 520 renforcée X-Ring",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport", "Hyper", "Track"],
    certifications: ["CE", "UN 38.3", "UL 2849"],
    rating: 4.9, review_count: 7, featured: true, bestseller: true, is_new: true
  },
  // ===== V. STORM BEE FAMILY =====
  {
    id: "surron-storm-bee-f-offroad",
    slug: "surron-storm-bee-f-motocross",
    nom: "Sur-Ron Storm Bee F (Pure Motocross)",
    nom_en: "Sur-Ron Storm Bee F (Pure Motocross)",
    brand: "Sur-Ron",
    category_label: "Motocross Électrique Adulte 22.5kW 110 km/h",
    category_label_en: "Adult Electric Motocross 22.5kW 110 km/h",
    description: "La moto de cross de taille adulte dans sa version pure off-road. Moteur 22.5 kW, batterie 104V 55Ah, vitesse max 110 km/h. Pas d'éclairage : dédiée au circuit et à l'entraînement motocross.",
    description_en: "Full-size adult motocross bike in pure off-road version. 22.5 kW motor, 104V 55Ah battery, 110 km/h top speed. No lighting: dedicated to track and motocross training.",
    highlight_subtitle: "22.5 kW • 110 km/h • 104V 55Ah • Motocross pur",
    highlight_subtitle_en: "22.5 kW • 110 km/h • 104V 55Ah • Pure Motocross",
    prix: 10990, prix_promo: 10790,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A2",
    license_label_fr: "Permis A2 (Usage Competition / Off-Road)",
    license_label_en: "A2 License (Competition / Off-Road Use)",
    autonomie_km: 60, autonomie_city_km: 75, autonomie_highway_km: 40,
    vitesse_max: 110, acceleration_0_100_s: 3.2, acceleration_0_50_s: 1.3,
    stock: 3, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 105, payload_kg: 130, temps_charge_h: 5.5,
    moteur: "Moteur électrique brushless 22.5 kW crête couple 600 Nm",
    batterie: "Pack Li-ion 5.72 kWh 104V 55Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 5.72, battery_voltage: 104, battery_removable: true,
    motor_nominal_kw: 12, motor_peak_kw: 22.5, motor_hp: 30.6, torque_nm: 600,
    motor_type: "Moteur brushless à aimants permanents compétition", transmission: "Chaîne 525 renforcée X-Ring",
    regen_braking: true, riding_modes: ["Standard", "Sport", "Race"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.8, review_count: 12, featured: true, bestseller: false, is_new: false
  },
  {
    id: "surron-storm-bee-e-enduro",
    slug: "surron-storm-bee-e-enduro-homologuee",
    nom: "Sur-Ron Storm Bee E (Enduro Homologuée Route)",
    nom_en: "Sur-Ron Storm Bee E (Enduro Road-Legal)",
    brand: "Sur-Ron",
    category_label: "Enduro Homologuée 125cc Taille Normale 104V",
    category_label_en: "Road-Legal Enduro 125cc Full-Size 104V",
    description: "Version enduro homologuée route de la Storm Bee. Équivalente 125cc de taille normale avec éclairage complet, support de plaque d'immatriculation et kit route. Batterie 104V 55Ah pour des performances de premier plan.",
    description_en: "Road-legal enduro version of the Storm Bee. Full-size 125cc equivalent with full lighting, license plate support and road kit. 104V 55Ah battery for top-tier performance.",
    highlight_subtitle: "Enduro Homologuée • 104V 55Ah • Éclairage complet",
    highlight_subtitle_en: "Road-Legal Enduro • 104V 55Ah • Full Lighting",
    prix: 11490, prix_promo: 11290,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A1_B",
    license_label_fr: "Permis A1 ou B + 7h (Équiv 125cc)",
    license_label_en: "License A1 or Car+7h (125cc Equivalent)",
    autonomie_km: 70, autonomie_city_km: 85, autonomie_highway_km: 50,
    vitesse_max: 100, acceleration_0_100_s: 3.5, acceleration_0_50_s: 1.5,
    stock: 4, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 110, payload_kg: 130, temps_charge_h: 5.5,
    moteur: "Moteur électrique brushless 22.5 kW crête couple 600 Nm",
    batterie: "Pack Li-ion 5.72 kWh 104V 55Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 5.72, battery_voltage: 104, battery_removable: true,
    motor_nominal_kw: 12, motor_peak_kw: 22.5, motor_hp: 30.6, torque_nm: 600,
    motor_type: "Moteur brushless à aimants permanents compétition", transmission: "Chaîne 525 renforcée X-Ring",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport", "Enduro"],
    certifications: ["CE", "UN 38.3", "UL 2849", "Euro 5"],
    rating: 4.7, review_count: 9, featured: false, bestseller: false, is_new: false
  },
  {
    id: "surron-storm-bee-r-supermoto",
    slug: "surron-storm-bee-r-supermoto",
    nom: "Sur-Ron Storm Bee R (Supermoto)",
    nom_en: "Sur-Ron Storm Bee R (Supermoto)",
    brand: "Sur-Ron",
    category_label: "Supermoto Électrique Adulte Jantes 17\" Pneu Sport",
    category_label_en: "Adult Electric Supermoto 17\" Sport Tires",
    description: "Version supermoto de la Storm Bee avec jantes 17 pouces et pneus sport pour la route. Suspensions raffermies et freins haute performance. La plus grosse supermoto électrique de la gamme Sur-Ron.",
    description_en: "Supermoto version of the Storm Bee with 17-inch rims and sport tires for road. Firmened suspension and high-performance brakes. The biggest electric supermoto in the Sur-Ron range.",
    highlight_subtitle: "Supermoto • Jantes 17\" • Pneu sport • 104V",
    highlight_subtitle_en: "Supermoto • 17\" Rims • Sport Tires • 104V",
    prix: 11490, prix_promo: 11290,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A2",
    license_label_fr: "Permis A2 (Jusqu'à 35 kW)",
    license_label_en: "A2 License (Up to 35 kW)",
    autonomie_km: 65, autonomie_city_km: 80, autonomie_highway_km: 45,
    vitesse_max: 105, acceleration_0_100_s: 3.3, acceleration_0_50_s: 1.4,
    stock: 3, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 108, payload_kg: 130, temps_charge_h: 5.5,
    moteur: "Moteur électrique brushless 22.5 kW crête couple 600 Nm",
    batterie: "Pack Li-ion 5.72 kWh 104V 55Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 5.72, battery_voltage: 104, battery_removable: true,
    motor_nominal_kw: 12, motor_peak_kw: 22.5, motor_hp: 30.6, torque_nm: 600,
    motor_type: "Moteur brushless à aimants permanents compétition", transmission: "Courroie carbone renforcée",
    regen_braking: true, riding_modes: ["Standard", "Sport", "Rain", "Track"],
    certifications: ["CE", "UN 38.3", "UL 2849"],
    rating: 4.8, review_count: 8, featured: true, bestseller: false, is_new: false
  },
  {
    id: "surron-storm-bee-104v-2026",
    slug: "surron-storm-bee-104v-2026-upgrade",
    nom: "Sur-Ron Storm Bee 104V (Mise à Niveau 2026)",
    nom_en: "Sur-Ron Storm Bee 104V (2026 Upgrade)",
    brand: "Sur-Ron",
    category_label: "Motocross 104V Cellules Haute Capacité 2026",
    category_label_en: "Motocross 104V High-Capacity Cells 2026",
    description: "Mise à niveau 2026 avec nouvelle gestion de batterie à cellules haute capacité et refroidissement liquide du moteur revu pour éviter la surchauffe en conditions compétitives. La Storm Bee dans sa version la plus aboutie.",
    description_en: "2026 upgrade with new high-capacity cell battery management and revised liquid engine cooling to prevent overheating in competitive conditions. The Storm Bee in its most refined version.",
    highlight_subtitle: "NOUVEAU 2026 • Refroidissement liquide • Cellules HC",
    highlight_subtitle_en: "NEW 2026 • Liquid Cooling • High-Capacity Cells",
    prix: 11990, prix_promo: 11790,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A2",
    license_label_fr: "Permis A2 (Jusqu'à 35 kW)",
    license_label_en: "A2 License (Up to 35 kW)",
    autonomie_km: 75, autonomie_city_km: 90, autonomie_highway_km: 50,
    vitesse_max: 115, acceleration_0_100_s: 3.0, acceleration_0_50_s: 1.2,
    stock: 5, stock_status: "in_showroom",
    delivery_time_label: "En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 103, payload_kg: 130, temps_charge_h: 5,
    moteur: "Moteur électrique brushless 22.5 kW refroidissement liquide couple 620 Nm",
    batterie: "Pack Li-ion 6.0 kWh 104V 58Ah (Lithium-Ion NMC haute capacité)",
    battery_kwh: 6.0, battery_voltage: 104, battery_removable: true,
    motor_nominal_kw: 12, motor_peak_kw: 22.5, motor_hp: 30.6, torque_nm: 620,
    motor_type: "Moteur brushless à aimants permanents compétition refroidissement liquide", transmission: "Chaîne 525 renforcée X-Ring",
    regen_braking: true, riding_modes: ["Standard", "Sport", "Race", "Endurance"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.9, review_count: 4, featured: true, bestseller: true, is_new: true
  },
  // ===== VI. ÉDITIONS SPÉCIALES & LIMITÉES =====
  {
    id: "surron-light-bee-x-black-edition",
    slug: "surron-light-bee-x-black-edition",
    nom: "Sur-Ron Light Bee X \"Black Edition\"",
    nom_en: "Sur-Ron Light Bee X \"Black Edition\"",
    brand: "Sur-Ron",
    category_label: "Édition Limitée Noire Mate Contrôleur Sport",
    category_label_en: "Limited Edition Matte Black Sport Controller",
    description: "Finition noire mate intégrale avec contrôleur paramétré d'usine pour une réponse de poignée plus agressive. Série limitée numérotée. Le look le plus agressif de la gamme Light Bee.",
    description_en: "Full matte black finish with factory-tuned controller for more aggressive throttle response. Numbered limited series. The most aggressive look in the Light Bee range.",
    highlight_subtitle: "Black Edition • Noire mate • Contrôleur sport • Limitée",
    highlight_subtitle_en: "Black Edition • Matte Black • Sport Controller • Limited",
    prix: 5490, prix_promo: 5290,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Off-Road Uniquement (Sans Permis)",
    license_label_en: "Off-Road Use Only (No License)",
    autonomie_km: 70, autonomie_city_km: 80, autonomie_highway_km: 45,
    vitesse_max: 80, acceleration_0_100_s: 5.0, acceleration_0_50_s: 2.1,
    stock: 3, stock_status: "in_showroom",
    delivery_time_label: "Série limitée - En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "Limited Edition - In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 53, payload_kg: 100, temps_charge_h: 4.5,
    moteur: "Moteur électrique brushless 8 kW crête contrôleur sport Black Edition",
    batterie: "Pack Li-ion 2.4 kWh 60V 40Ah (Lithium-Ion NMC)",
    battery_kwh: 2.4, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 4, motor_peak_kw: 8, motor_hp: 10.9, torque_nm: 266,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 428H renforcée or noire",
    regen_braking: true, riding_modes: ["Standard", "Sport", "Black Edition Aggressive"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.9, review_count: 11, featured: true, bestseller: false, is_new: false
  },
  {
    id: "surron-light-bee-x-kling-edition",
    slug: "surron-light-bee-x-kling-edition-asia",
    nom: "Sur-Ron Light Bee X \"K領 Edition\" (Asia Exclusive)",
    nom_en: "Sur-Ron Light Bee X \"K領 Edition\" (Asia Exclusive)",
    brand: "Sur-Ron",
    category_label: "Édition Exclusive Asie Or/Noir Protections Carbone",
    category_label_en: "Asia Exclusive Gold/Black Edition Carbon Frame Guards",
    description: "Kit déco exclusif doré/noir avec protections de cadre en carbone livrées d'origine. Édition exclusive marché asiatique désormais disponible en Europe via notre showroom. Pièces carbone introuvables ailleurs.",
    description_en: "Exclusive gold/black decal kit with carbon frame guards included as standard. Asia-exclusive edition now available in Europe through our showroom. Carbon parts found nowhere else.",
    highlight_subtitle: "K領 Edition • Or/Noir • Protections carbone • Exclusive",
    highlight_subtitle_en: "K領 Edition • Gold/Black • Carbon Guards • Exclusive",
    prix: 5290, prix_promo: 5090,
    eco_bonus_eligible: true, max_eco_bonus: 400,
    type: "moto", license_category: "none",
    license_label_fr: "Usage Off-Road Uniquement (Sans Permis)",
    license_label_en: "Off-Road Use Only (No License)",
    autonomie_km: 70, autonomie_city_km: 80, autonomie_highway_km: 45,
    vitesse_max: 80, acceleration_0_100_s: 5.2, acceleration_0_50_s: 2.2,
    stock: 2, stock_status: "in_showroom",
    delivery_time_label: "Édition exclusive - En stock au Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "Exclusive Edition - In stock at Paris Showroom • 48-72h delivery",
    poids_kg: 54, payload_kg: 100, temps_charge_h: 4.5,
    moteur: "Moteur électrique brushless 8 kW crête",
    batterie: "Pack Li-ion 2.4 kWh 60V 40Ah (Lithium-Ion NMC)",
    battery_kwh: 2.4, battery_voltage: 60, battery_removable: true,
    motor_nominal_kw: 4, motor_peak_kw: 8, motor_hp: 10.9, torque_nm: 266,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 428H renforcée",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport"],
    certifications: ["CE", "UN 38.3"],
    rating: 4.8, review_count: 6, featured: true, bestseller: false, is_new: false
  },
  {
    id: "surron-ultra-bee-anniversary-edition",
    slug: "surron-ultra-bee-limited-anniversary-edition",
    nom: "Sur-Ron Ultra Bee Limited Anniversary Edition",
    nom_en: "Sur-Ron Ultra Bee Limited Anniversary Edition",
    brand: "Sur-Ron",
    category_label: "Édition Anniversaire Moyeux Anodisés Suspensions HP",
    category_label_en: "Anniversary Edition Anodized Hubs HP Suspension",
    description: "Édition limitée anniversaire avec moyeux de roues anodisés et suspensions ajustables haut de gamme. Célébrez l'expansion internationale de la marque avec cette pièce de collection unique. Numérotée et certifiée.",
    description_en: "Limited anniversary edition with anodized wheel hubs and premium adjustable suspension. Celebrate the brand's international expansion with this unique collector's item. Numbered and certified.",
    highlight_subtitle: "Anniversary • Moyeux anodisés • Suspensions HP • Numérotée",
    highlight_subtitle_en: "Anniversary • Anodized Hubs • HP Suspension • Numbered",
    prix: 11490, prix_promo: 11290,
    eco_bonus_eligible: true, max_eco_bonus: 900,
    type: "moto", license_category: "A1_B",
    license_label_fr: "Permis A1 ou B + 7h (Équiv 125cc)",
    license_label_en: "License A1 or Car+7h (125cc Equivalent)",
    autonomie_km: 100, autonomie_city_km: 120, autonomie_highway_km: 70,
    vitesse_max: 95, acceleration_0_100_s: 3.8, acceleration_0_50_s: 1.6,
    stock: 2, stock_status: "in_showroom",
    delivery_time_label: "Édition limitée numérotée - Showroom Paris 17e • Livraison 48-72h",
    delivery_time_label_en: "Numbered Limited Edition - Paris Showroom • 48-72h delivery",
    poids_kg: 86, payload_kg: 140, temps_charge_h: 5,
    moteur: "Moteur électrique brushless 12.5 kW crête couple 400 Nm édition spéciale",
    batterie: "Pack Li-ion 4.44 kWh 74V 60Ah (Lithium-Ion NMC haute décharge)",
    battery_kwh: 4.44, battery_voltage: 74, battery_removable: true,
    motor_nominal_kw: 6, motor_peak_kw: 12.5, motor_hp: 17, torque_nm: 400,
    motor_type: "Moteur brushless à aimants permanents haute puissance", transmission: "Chaîne 520 renforcée X-Ring or noire",
    regen_braking: true, riding_modes: ["Eco", "Standard", "Sport", "Anniversary Pro"],
    certifications: ["CE", "UN 38.3", "UL 2849", "Euro 5"],
    rating: 5.0, review_count: 3, featured: true, bestseller: false, is_new: false
  },
];

// Generate TypeScript
function genProduct(p) {
  const img = '"/images/products/surron-light-bee-x.jpg"';
  return `  {
    id: "${p.id}",
    slug: "${p.slug}",
    nom: ${JSON.stringify(p.nom)},
    nom_en: ${JSON.stringify(p.nom_en)},
    brand: "${p.brand}",
    category_label: ${JSON.stringify(p.category_label)},
    category_label_en: ${JSON.stringify(p.category_label_en)},
    description: ${JSON.stringify(p.description)},
    description_en: ${JSON.stringify(p.description_en)},
    highlight_subtitle: ${JSON.stringify(p.highlight_subtitle)},
    highlight_subtitle_en: ${JSON.stringify(p.highlight_subtitle_en)},
    prix: ${p.prix},
    prix_promo: ${p.prix_promo},
    eco_bonus_eligible: ${p.eco_bonus_eligible},
    max_eco_bonus: ${p.max_eco_bonus},
    image_url: ${img},
    images: [${img}],
    type: "${p.type}",
    license_category: "${p.license_category}",
    license_label_fr: ${JSON.stringify(p.license_label_fr)},
    license_label_en: ${JSON.stringify(p.license_label_en)},
    autonomie_km: ${p.autonomie_km},
    autonomie_city_km: ${p.autonomie_city_km},
    autonomie_highway_km: ${p.autonomie_highway_km},
    vitesse_max: ${p.vitesse_max},
    acceleration_0_100_s: ${p.acceleration_0_100_s},
    acceleration_0_50_s: ${p.acceleration_0_50_s},
    stock: ${p.stock},
    stock_status: "${p.stock_status}",
    delivery_time_label: ${JSON.stringify(p.delivery_time_label)},
    delivery_time_label_en: ${JSON.stringify(p.delivery_time_label_en)},
    poids_kg: ${p.poids_kg},
    payload_kg: ${p.payload_kg},
    temps_charge_h: ${p.temps_charge_h},
    moteur: ${JSON.stringify(p.moteur)},
    batterie: ${JSON.stringify(p.batterie)},
    battery_specs: {
      capacity_kwh: ${p.battery_kwh},
      voltage: ${p.battery_voltage},
      removable: ${p.battery_removable},
      cell_type: "LG/Samsung 21700 High Discharge",
      charge_time_home_h: ${p.temps_charge_h},
      charge_time_fast_min: undefined,
      warranty_years: 2,
      warranty_km: 20000,
      ip_rating: "IP65"
    },
    motor_specs: {
      power_nominal_kw: ${p.motor_nominal_kw},
      power_peak_kw: ${p.motor_peak_kw},
      power_hp: ${p.motor_hp},
      torque_nm: ${p.torque_nm},
      motor_type: ${JSON.stringify(p.motor_type)},
      transmission: ${JSON.stringify(p.transmission)},
      regen_braking: ${p.regen_braking},
      riding_modes: ${JSON.stringify(p.riding_modes)}
    },
    certifications: ${JSON.stringify(p.certifications)},
    available_options: [
      {
        id: "opt-${p.id}-1",
        name: "Pack Entretien Sérénité & Pièces d'Usure 2 Ans",
        name_en: "2-Year Peace-of-Mind Maintenance Pack",
        price: 190,
        description: "Couvre les plaquettes, révisions semestrielles et réglages en centre agréé.",
        description_en: "Covers brake pads, bi-annual inspections, and tuning in authorized centers.",
        category: "security"
      },
      {
        id: "opt-${p.id}-2",
        name: "Antivol Connecté GPS Tracker 4G avec Alarme 110dB",
        name_en: "4G GPS Tracker & 110dB Anti-Theft Alarm",
        price: 149,
        description: "Géolocalisation en temps réel sur smartphone et détection de mouvement suspect.",
        description_en: "Real-time smartphone geolocation and anti-tamper shock sensor.",
        category: "security"
      }
    ],
    reviews: [
      {
        id: "rev-${p.id}-1",
        author: "Lucas M. (Paris)",
        rating: ${p.rating},
        date: "15 Janvier 2026",
        verified: true,
        title: "Machine exceptionnelle et sensations garanties",
        title_en: "Exceptional machine and guaranteed thrills",
        comment: "Rapport qualité-prix imbattable pour ce type de machine. La livraison était impeccable et le SAV réactif. Je recommande sans hésiter.",
        comment_en: "Unbeatable value for money for this type of machine. Delivery was flawless and after-sales service responsive. Highly recommend.",
        real_range_tested_km: ${Math.round(p.autonomie_km * 0.85)},
        location: "Île-de-France"
      }
    ],
    rating: ${p.rating},
    review_count: ${p.review_count},
    featured: ${p.featured},
    bestseller: ${p.bestseller},
    is_new: ${p.is_new}
  }`;
}

const output = products.map(genProduct).join(',\n');
console.log(output);
